### ISSUE TITLE
eayunstack-tools/utils.py is_unknown() 报错

### ISSUE THREAD

**Issue by blkart** [blkart/eayunstack-tools#3]
- 引用is_unknown()函数时,报以下错误:

```
  Traceback (most recent call last):
  File "/usr/bin/eayunstack", line 9, in <module>
    load_entry_point('eayunstack-tools==0.0.1', 'console_scripts', 'eayunstack')()
  File "build/bdist.linux-x86_64/egg/eayunstack_tools/main.py", line 35, in main
  File "build/bdist.linux-x86_64/egg/eayunstack_tools/main.py", line 29, in create_parser
  File "build/bdist.linux-x86_64/egg/eayunstack_tools/doctor/__init__.py", line 6, in make
  File "build/bdist.linux-x86_64/egg/eayunstack_tools/utils.py", line 19, in make_subcommand
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.linux-x86_64/egg/eayunstack_tools/doctor/all.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/eayunstack_tools/doctor/stack.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/eayunstack_tools/doctor/stack_func.py", line 16, in <module>
  File "build/bdist.linux-x86_64/egg/eayunstack_tools/doctor/utils.py", line 13, in get_node_role
  File "build/bdist.linux-x86_64/egg/eayunstack_tools/utils.py", line 114, in is_unknown
IndexError: list index out of range
```

**Comment by blkart** [comment]
### 问题分析
- 该问题与上游_get_roles()函数bug有关,当/.node-role内容为空时,_get_roles()返回值也为空,预期返回值应为"[5]".如上游修复该bug,该issue可不做任何处理直接关闭.
